language: csharp
solution: Stripe.sln
install:
  - nuget restore Stripe.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Stripe.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./test/Stripe.Tests/bin/Release/Stripe.Tests.dll